### ISSUE TITLE
Help to write a hello world

### ISSUE THREAD

**Issue by danielgatis** [akiradeveloper/lol#187]
Hi,

I read the entire book (https://akiradeveloper.github.io/lol/) but I still have doubts about how to make a simple app.

Could you make an example of a `hello world` implementing the "RaftApp" methods?

How is the workflow of adding a new node to the cluster dynamically?

tks.

**Comment by akiradeveloper** [comment]
Hi @danielgatis,

To write a hello-world `RaftApp`, reading kvs-server in kvs crate would be helpful. This server is used in integration_tests which includes cluster management.

Also, much simpler example is ready in develop as well https://github.com/akiradeveloper/lol/pull/184/files

Both `RaftApp` implementations are based on `RaftAppCompat`. This is a `RaftApp` with a limited capability which implements `RaftApp`. This compat layer is simpler to use because notions like `SnapshotTag` (written in lol-book) aren't involved. Actually, in our in-house project we use this. However, if you want to implement more efficient application, this compat layer isn't recommended.

As for the cluster management, there are two phases. 1) Cluster initialization 2) Add/Remove servers

Let's explain 2) first. Suppose your cluster has three nodes n0,n1,n2 and you want to add n3, sending a request (AddServer n3) to any of the three nodes will eventually form a new cluster n0,n1,n2,n3.

Then explain 1). When you start a server it doesn't belong to any cluster. Suppose you start a server n0, then sending (AddServer n0) to n0 will form a initial cluster with one node n0. This is called cluster bootstrapping.

So how to send (AddServer x) request? The quickest way to do this is use lol-admin command. lol-admin has sub commands like add-server and remove-server and you can use them. You can also send AddServer gRPC directly.

**Comment by danielgatis** [comment]
@akiradeveloper wow! thank you so much for the detailed instructions.

Did use some kind of service discovery to find and add/remove new nodes? or did you do this manually through the admin cmd?

**Comment by danielgatis** [comment]
@akiradeveloper sorry, one more question.

In the following example, what represents each input and output?

```
    async fn process_message(&self, request: &[u8]) -> anyhow::Result<Vec<u8>> { // what this return represents?
        println!("raft: process {}", request.len());
        Ok(vec![])
    }
    
    async fn apply_message(
        &self,
        request: &[u8], // this is a messages sended by the client as bytes, right?
        apply_index: Index, // what is this apply_index? what a suposed to do with this?
    ) -> anyhow::Result<(Vec<u8>, Option<Vec<u8>>)> { // what these return represents?
        unimplemented!()
    }
    
    async fn install_snapshot(
        &self,
        snapshot: Option<&[u8]>, // serialized bytes of the snapshot?
        apply_index: Index, // what is this apply_index? what a suposed to do with this?
    ) -> anyhow::Result<()> {
        Ok(())
    }
    
    async fn fold_snapshot(
        &self,
        old_snapshot: Option<&[u8]>,
        requests: Vec<&[u8]>,
    ) -> anyhow::Result<Vec<u8>> {
        Ok(vec![])
    }
```

What is the difference between `install_snapshot` and `fold_snapshot`? when it is called in the life cycle? I need to implement both in a compat app?

tks.

**Comment by akiradeveloper** [comment]
@danielgatis 

> Did use some kind of service discovery to find and add/remove new nodes? or did you do this manually through the admin cmd?

We find the cluster manually in adding or removing nodes and use connection::gateway in normal clients. Gateway is a utility that tracks the cluster membership by querying it periodically.

Cluster discovery is an interesting topic and you can find a discussion in 6.1 of [this paper](https://raw.githubusercontent.com/ongardie/dissertation/master/online.pdf). It is actually case-by-case and there is not a perfect solution.

**Comment by akiradeveloper** [comment]
@danielgatis 

Raft algorithm is based on log replication. The log is replicated to the nodes in the same order and they are applied to each state machine in the same order, results in the same state. Compat layer is a direct implementation of this concept.

To explain, let Snapshot(k) is a folded (folding a word from functional programming) value of the Log[1,k]. Then Snapshot must satisfy fold(Snapshot(x), Log[x+1,n]) = fold(Snapshot(y), Log[y+1,n]) for any x,y in 1 to n.

Then answer your question,

```rust
    async fn apply_message(
        &self,
        request: &[u8], // this is a messages sended by the client as bytes, right? => YES
        apply_index: Index, // what is this apply_index? what a suposed to do with this? => index in the Log
    ) -> anyhow::Result<(Vec<u8>, Option<Vec<u8>>)> { // what these return represents? => First one is a returned value of the application and the second value is related to copy snapshot described in the lol-book.
        unimplemented!()
    }
    
    async fn install_snapshot(
        &self,
        snapshot: Option<&[u8]>, // serialized bytes of the snapshot? => YES. It can be none.
        apply_index: Index, // what is this apply_index? what a suposed to do with this? => k in the explanation. i.e. This function installs Snapshot(k)
    ) -> anyhow::Result<()> {
        Ok(())
    }
```

> What is the difference between install_snapshot and fold_snapshot? when it is called in the life cycle? I need to implement both in a compat app?

I believe the difference was explained. Since normal Raft application uses snapshot, install_snapshot is MUST but fold_snapshot isn't if you don't use it.

In Raft, snapshot is needed for slow node to catch up fast (and data compression). In lol, snapshot can be created in two ways (fold and copy).  If you choose to use fold snapshot, snapshot is created (`fold_snapshot` is called) periodically in background thread. `install_snapshot` is called only when the node is slow.

You can disable fold snapshot by setting this config to 0.

```rust
    /// The interval that compaction runs.
    /// You can set this to 0 and fold snapshot will never be created.
    pub compaction_interval_sec: u64,
```

`process_message` is a special version of apply_message. If the query doesn't side effects, it doesn't need to put on log so to eventually be applied by state machine, but put on fast path specialized for non-side effective queries. This is an implementation of technique described in 6.4 of said paper.

**Comment by danielgatis** [comment]
Thanks so much, you were very clear in your explanation.
