### ISSUE TITLE
Gateway documentation?

### ISSUE THREAD

**Issue by GothAck** [akiradeveloper/lol#274]
Trying to get started with lol and the Gateway sound like a cool thing, however documentation is sparse and I'm unsure how to set up the Gateway and call gGRPC methods through it... Any pointers?

**Comment by akiradeveloper** [comment]
@GothAck Here is the documentation https://akiradeveloper.github.io/lol/gateway.html but it may be a little unkind for new comers.

Gateway is a kind of Tonic's [Channel](https://docs.rs/tonic/latest/tonic/transport/struct.Channel.html) but automatically directs the client request to the leader node. In Raft, all requests are processed by leader. In lol, request that is sent to any of the follower nodes are redirected to the leader but this is not the best result because we needs one extra hop.

Gateway polls the current membership from the cluster in interval and registers the leader to the [balance channel](https://docs.rs/tonic/latest/tonic/transport/struct.Channel.html#method.balance_channel) which Gateway holds internally.  Because it pretends to be a `Channel` by implementing as 

```rust
impl Service<http::Request<BoxBody>> for super::Gateway {
    type Response = <Channel as Service<http::Request<BoxBody>>>::Response;
    type Error = <Channel as Service<http::Request<BoxBody>>>::Error;
    type Future = <Channel as Service<http::Request<BoxBody>>>::Future;
    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Service::poll_ready(&mut self.chan, cx)
    }
    fn call(&mut self, request: http::Request<BoxBody>) -> Self::Future {
        Service::call(&mut self.chan, request)
    }
}
```

user can use instantiated Gateway just like a normal `Channel`.

My teammate had the same question too and he understood the usage after reading this test code

```rust
async fn test_gateway() {
    let env = init_cluster(1);
    let connector = gateway_v2::Connector::new(|id| Endpoint::from(id.clone()));
    let gateway = connector.connect(env.get_node_id(0).parse().unwrap());
    env.start(1, kvs_server(vec![]));
    env.start(2, kvs_server(vec![]));
    Admin::to(0, env.clone()).add_server(1).unwrap();
    Admin::to(0, env.clone()).add_server(2).unwrap();
    tokio::time::sleep(Duration::from_secs(6)).await;

    let mut cli1 = RaftClient::new(gateway.clone());
    let mut cli2 = RaftClient::new(gateway);
    let res = cli1.request_cluster_info(ClusterInfoReq {}).await;
    assert!(res.is_ok());
    let res = cli2.request_cluster_info(ClusterInfoReq {}).await;
    assert!(res.is_ok());
```

https://github.com/akiradeveloper/lol/blob/master/integration-tests/tests/gateway.rs

If this makes sense to you, I will add this code to the doc comment.

**Comment by akiradeveloper** [comment]
I am reworking.
